name: Feed Scheduler
on:
  # Acts when main branch was pushed or pr accepted.
  push:
    branches: [ $default-branch ]
    paths:
      - src
      - .github/workflows/scheduler.yml
  pull_request:
    branches: [ $default-branch ]
  # Acts when every 08:00 am.
  schedule:
    - cron: "00 23 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}
          ${{ runner.os }}-build
          ${{ runner.os }}-
    - name: Install dependencies
      run: npm install
    - name: Execute task
      run: npm start
      env:
        CI: true
        
        WEBHOOKS: ${{ secrets.WEBHOOKS }}
